### PR TITLE
Update to ink2.0 and latest substrate

### LINKED ISSUE #6: Update to `ink!` 2.0 and latest substrate
/cc @liuchengxu

### PR DESCRIPTION
**Pull request by liuchengxu**
- [x] Update the syntax to ink2.0 and use the latest substrate.
- [x] Rebuild the project struct based on the template genreated by https://github.com/paritytech/cargo-contract.
- [ ] Make it compile under paritytech/ink.
    - [x] The old `env.dispatch_call` is missing in ink2.0, and I added `invoke_runtime` to `env_access` to make it build, see https://github.com/liuchengxu/ink/commit/b74f789ff251ca704dd17e6efa771352abb27a51. Please see if it's the on the right track @ascjones .
- [ ] Add back the tests.
    - [x] `src/lib.rs`
           Due to the removal of `Debug` trait(https://github.com/paritytech/ink/pull/291), previous `assert_eq!(...)` is unusable now. Use `assert!` instead.
    - [ ] `examples/calls`
            `env().dispatched_calls()` replacement in examples/calls test.
- [ ] Replace the old `srml` words.

-----------

I have just tested with the latest substrate. The dispatched called runs into an internal error, the old version is fine. I'm not sure what is wrong internally. Help needed here. @ascjones 

Close #6

### CODE REVIEW

**Comment by ascjones** [comment]
> The dispatched called runs into an internal error

In the contracts runtime - does it print to the terminal what the error was? I could run it myself but won't get to it today

**Comment by liuchengxu** [comment]
The error message is not much helpful.

```
...
2019-12-05 10:48:33.159 main-tokio-4 DEBUG runtime  DispatchError
2019-12-05 10:48:33.159 main-tokio-4 DEBUG runtime  17
2019-12-05 10:48:33.159 main-tokio-4 DEBUG runtime  0
2019-12-05 10:48:33.159 main-tokio-4 DEBUG runtime  during execution
```

I have a contract using `dispatch_call` in the old `env` works well previously, but when I get it updated to the ink2.0 with `invoke_runtime` added, the same error occured. Since the contracts runtime is basically unchanged, something is wrong with either `env2` or my `invoke_runtime` addition then.

**Comment by liuchengxu** [comment]
Any news about this thread? @ascjones We currently are working on migrating ink1.0 to ink2.0 and just get stuck at this issue of missing working `dispatch_call` in ink2.0.

**Comment by ascjones** [comment]
@liuchengxu I will have a look at this today

**Comment by ascjones** [comment]
It's failing to decode the `Call` here: https://github.com/paritytech/substrate/blob/f588aa53af54029c6b45f26342204482f2e946c5/frame/contracts/src/wasm/runtime.rs#L632

The contents of the buffer is `0x00ff1cbd2d43530a44705ad088af313e18f80b53ef16b36177cd4b77b846f2a5f07c00` if you want to try and figure out why it can't decode.

Otherwise I will figure out why this is happening tomorrow.

**Comment by liuchengxu** [comment]
Sure, I'll have a look too.

**Comment by liuchengxu** [comment]
Thanks for the clue, @ascjones . I have figured it out. Unlike the old example, now the `transfer_call` should be wrapped in the top enum `Call`, see https://github.com/paritytech/ink-types-node-runtime/pull/7/commits/049cf06bcbfd19ff0906a4f22bc6320cdb3fa066. If you have no problem with the added `invoke_runtime`, I can prepare a PR to ink! and then we could continue this example.

**Comment by ascjones** [comment]
@liuchengxu yes just spotted that myself!

**Comment by jaybutera** [comment]
@liuchengxu any progress on this PR in ink?

**Comment by liuchengxu** [comment]
@jaybutera I believe this PR will wait until https://github.com/paritytech/ink/issues/297 is resolved and `invoke_runtime` is exposed in ink2. Once `invoke_runtime` is supported in ink2, I should be able to finish the rest job of this PR soon.

**Comment by ascjones** [comment]
@liuchengxu you should be able to finish up this PR now since the new `ink!` env imrpovements

**Comment by liuchengxu** [comment]
@ascjones Great! I'll take a look soon.

**Comment by liuchengxu** [comment]
@ascjones I have updated to the latest ink!, but I still have some questions:

- Can we reuse the current `AccountId32` from `sp_core` instead of duplicating it?
- About the `calls` test, should we use the `get_runtime_storage()` function? I did some try, but haven't made it work, the storage is already None :(.

**Comment by ascjones** [comment]
@liuchengxu apologies for the delay. 

> Can we reuse the current AccountId32 from sp_core instead of duplicating it?

Yes we can. Recent optimizations in `cargo-contract` I've been working on allow us now to use substrate types directly. In fact we can even use `Address` to avoid the duplication here.

> About the calls test, should we use the get_runtime_storage() function? I did some try, but haven't made it work, the storage is already None

No because the test environment doesn't fully emulate the substrate runtime. `get_runtime_storage()` will only return anything written into the test runtime storage directly.

I'll merge this because I have a follow up which is based on it, which removes the `Address` copy.

**Review by ascjones — APPROVED** [review]
LGTM

**Pull request merged**
